server:
  port: 11300

spring:
  application:
    name: logistics-user-server
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: http://172.16.1.160:8848/
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://172.16.1.160:9411/